# Generated by Django 4.0.4 on 2022-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_borrowedequipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedequipment',
            old_name='user',
            new_name='name',
        ),
    ]
